config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "posts#index"
  get "categories/:id/show" => "categories#show", as: :categories_show
  get "posts/new_anime" => "posts#new_anime"
  post "posts/:post_id/favorites/" => "favorites#create", as: :post_favorites
  delete "posts/:post_id/favorites" => "favorites#destroy"
  get "users/:user_id/reference" => "users#reference", as: :user_reference
  get "animes/search" => "animes#search", as: :anime_search
  
    resources :users, only:  [:show]
    resources :animes, only: [ :index, :show, :new, :create] do 
      resources :posts, only: [ :new, :create, :index, :show, :edit, :update, :destroy] do
      resources :posts, only: [:search] 
        collection do
        get 'search'
      end
    end
  end
end

app/models/anime.rb
class Anime < ApplicationRecord
  has_many :posts, dependent: :destroy
  belongs_to :category
  validates :title, presence: true
  validates :image, presence: true
  validates :detail, presence: true
  validates :category_id, presence: true
  validates_uniqueness_of :title
  mount_uploader :image, ImageUploader

  # ヘッダー検索
  def self.search(search)
    if search
      Anime.where('title LIKE(?)', "%#{search}%")
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :animes
  validates :name, presence: true
  validates_uniqueness_of :name
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  # validates_uniqueness_ofによって、post_idとuser_idの組が1組しかないようにバリデーション
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :anime
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  validates :title, presence: true
  validates :review, presence: true
  validates :rate, presence: true
  validates :user_id, presence: true
  validates :anime_id, presence: true
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 12 }
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post

end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :authenticate_user!,  only:[:new, :create]
  
  def index
    @anime = Anime.find(params[:id])
    @genre = @anime.genre
  end

  def new
    @anime = Anime.new
    @categories = Category.all
  end

  def create
    @anime = Anime.new(anime_params)
    if @anime.save
      redirect_to root_path
    else
      render:new
    end
  end

  def show
    @anime = Anime.find(params[:id])
    @post = @anime.posts.order(id: "desc").limit(3)
    @all_ranks = Anime.find(Post.group(:anime_id).order('count(anime_id) desc').limit(5).pluck(:anime_id))
    @categories = Category.all
  end

  def search
    @anime = Anime.search(params[:search])
  end

  private
  def anime_params
    params.require(:anime).permit(:title, :image, :genre, :detail,:category_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :category


  def category
    @categories = Category.all
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @all_ranks = Anime.find(Post.group(:anime_id).order('count(anime_id) desc').limit(5).pluck(:anime_id))
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorites

  def create
    @favorite = current_user.favorites.create(post_id: params[:post_id])
    @favorite.save
  end

  def destroy
    @favorite = Favorite.find_by(post_id: params[:post_id], user_id: current_user.id)
    @favorite.destroy
  end

  def set_favorites
    @post = Post.find(params[:post_id])
    @id_name = "#favorites_buttons_#{@post.id}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :new_anime, :edit]
  before_action :set_action, only:[:show, :edit, :update, :destroy]
  
  def index
    @posts = Post.all.page(params[:page]).order(id: 'desc').per(5)
    @anime =  Anime.find(Post.group(:anime_id).order('count(anime_id) desc').limit(12).pluck(:anime_id))
    @all_ranks = Anime.find(Post.group(:anime_id).order('count(anime_id) desc').limit(5).pluck(:anime_id))
    @categories = Category.all
  end

  def new_anime
    @post = Post.new
    @anime = Anime.all
  end


  def new
    @post = Post.new
    @anime = Anime.find(params[:anime_id])
  end

  def create
    # @anime = Anime.find_by(id: params[:anime_id])
    @anime = Anime.all
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else 
      render :new_anime
    end
  end

  def show
    @all_ranks = Anime.find(Post.group(:anime_id).order('count(anime_id) desc').limit(5).pluck(:anime_id))
    @anime = Anime.find(params[:anime_id]) 
    @categories = Category.all
    # @anime_other = @anime.posts.where.not(user_id: current_user.id)
  end
  
  def edit
    @anime = @post.anime.id
  end

  def update
    @anime = @post.anime.id
    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @post.delete
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @animes = Anime.where('title LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def set_action
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :review, :rate, :anime_id).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @all_posts = @user.posts
    @posts = @user.posts.page(params[:page]).order(id: 'desc').per(5)
    @all_ranks = Anime.find(Post.group(:anime_id).order('count(anime_id) desc').limit(5).pluck(:anime_id))
  end
  
  def reference
    @user = current_user
    @references = @user.favorited_posts
  end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animes/new.html.haml
.anime
  .anime__text.py-3
    新規アニメの登録
  .anime__form.my-4
    = form_for @anime do |f|
      .anime__form__field
        = f.label :ジャンル, class:"genre__label"
        %span.genre__label__tag
          必須
        %br/  
        = f.collection_select(:category_id, @categories, :id, :name, class:"genre__field", :prompt => "選択して下さい")
        %br/
      .anime__form__field
        = f.label :作品画像, class:"image__label"
        %span.image__label__tag
          必須
        %br/
        = f.file_field :image, class:"image__field"

      .anime__form__field
        = f.label :アニメタイトル, class:"title__label"
        %span.title__label__tag
          必須
        %br/
        = f.text_field :title, autofocus: true, class:"title__field", placeholder: "アニメタイトルを入力して下さい"
      .anime__form__field
        = f.label :あらすじ, class:"detail__label"
        %span.detail__label__tag
          必須
        %br/
        = f.text_area :detail, autofocus: true, class: "detail__field", placeholder: "アニメのあらすじを入力してください", rows: "10", cols: "60"
      
      .anime__form__submit
        = f.submit "新規アニメ登録", class:"anime__submit"
  
  

app/views/animes/search.html.haml
.anime__search.my-3 
  .anime__search__main
    .anime__search__main__text.my-3
      検索結果 
      - if @anime.exists?
        - @anime.each do |anime|
          = link_to(anime_path(anime), class: "anime__search__main__link")do
            .anime__search__content
              .anime__search__content__left 
                = image_tag anime.image.url, class: "anime__search__content__left__image"
                .anime__search__content__right
                  .anime__search__content__right__title.mb-2
                    = anime.title
                  %span.anime__search__content__right__rate
                  評価:  
                  %span{:id => "rate-#{anime.id}"}
                  :javascript
                    $('#rate-#{anime.id}').raty({
                      size: 36,
                      starOff:  '#{asset_path('star-off.png')}',
                      starOn : '#{asset_path('star-on.png')}',
                      starHalf: '#{asset_path('star-half.png')}',
                      half: true,
                      readOnly: true,
                      score: #{anime.posts.average(:rate).to_f.round(1)}  
                    });
                  = anime.posts.average(:rate).to_f.round(1)
                  .anime__search__content__right__title__count.my-2
                    口コミ
                    = "#{anime.posts.count}" + "件"
                  .category__wrapper__main__block__righ__category.pb-3
                    = "ジャンル:#{anime.category.name}"
      - else
        .anime__search__else
          一致するアニメはありませんでした。

app/views/animes/show.html.haml
.anime__show.mb-3
  -# posts/showと同じクラス
  .show__wrapper__main
    .show__wrapper__main__anime.mb-3
      .show__wrapper__main__anime__image
        = image_tag @anime.image.url
      .show__wrapper__main__anime__item
        .show__wrapper__main__anime__item__title
          = @anime.title
        .show__wrapper__main__anime__item__count
          口コミ数
          = "#{@anime.posts.count}" + "件"
        .show__wrapper__main__anime__item__star
          %span.show__review__rate
            みんなの評価:  
            %span{:id => "show-rate-#{@anime.id}"}
            :javascript
              $('#show-rate-#{@anime.id}').raty({
                size: 36,
                starOff:  '#{asset_path('star-off.png')}',
                starOn : '#{asset_path('star-on.png')}',
                starHalf: '#{asset_path('star-half.png')}',
                half: true,
                readOnly: true,
                score: #{@anime.posts.average(:rate).to_f.round(1)}  
              });
          = @anime.posts.average(:rate).to_f.round(1)

  .anime__show__main
    .anime__show__main__text.my-3
      = "#{@anime.title}のあらすじ"
      .anime__show__main__detail.mt-3
        = @anime.detail
    .anime__show__main__review.my-3
      .anime__show__main__review__text.my-3.px-3
        = "#{@anime.title}の感想"
        = link_to "[感想を投稿する]", new_anime_post_path(@anime), class: "anime__show__main__review__link"
      - @post.each do |post|
        = link_to(anime_post_path(post.anime, post))do
          .anime__show__main__review__block
            .anime__show__main__review__block__title
              = post.title
            .anime__show__main__review__block__review
              = post.review.truncate(175)
            - if post.review.length >= 175
              = link_to '>>続きを読む', anime_post_path(post.anime, post), class: "anime__show__main__review__block__review__link"
            .anime__show__main__review__block__name
              = post.user.name
              %span.anime__show__main__review__block__name__time.mx-3
                = post.created_at.strftime("%Y年%m月%d日 %H時%M分")
              %span.anime__show__main__review__block__name__rate.mx-1
                評価:
                %span{:id => "other-rate-#{post.id}"}
                :javascript
                  $('#other-rate-#{post.id}').raty({
                    size: 36,
                    starOff:  '#{asset_path('star-off.png')}',
                    starOn : '#{asset_path('star-on.png')}',
                    starHalf: '#{asset_path('star-half.png')}',
                    half: true,
                    readOnly: true,
                    score: #{post.rate}
                  });
              = post.rate
              %span.anime__show__main__review__block__name__length
                = post.review.length.to_s + "文字"  
  .main.flex 
    = render partial: 'posts/right'   
  :css
    .main__right {
      position: absolute;
      top: 352px;
      right: 250px;
    }
    .show__wrapper__main__anime:hover {
      opacity: 1;
      transition: none;
    }

app/views/categories/show.html.haml
.category__wrapper.pb-2
  .category__wrapper__text.my-3
    = "#{@category.name}のおすすめアニメ一覧"
  .category__wrapper__header.p-3
    .category__wrapper__main
      - @category.animes.each do |category|
        = link_to(anime_path(category), class: "category__wrapper__main__link")do
          .category__wrapper__main__block
            .category__wrapper__main__block__left
              = image_tag category.image.url
            .category__wrapper__main__block__right
              .category__wrapper__main__block__right__title.mb-2
                = category.title
                
              %span.category__wrapper__main__block__right__rate
                評価:  
                %span{:id => "rate-#{category.id}"}
                :javascript
                  $('#rate-#{category.id}').raty({
                    size: 36,
                    starOff:  '#{asset_path('star-off.png')}',
                    starOn : '#{asset_path('star-on.png')}',
                    starHalf: '#{asset_path('star-half.png')}',
                    half: true,
                    readOnly: true,
                    score: #{category.posts.average(:rate).to_f.round(1)}  
                  });
                = category.posts.average(:rate).to_f.round(1)
                .category__wrapper__main__block__right__count.my-2
                  口コミ
                  = "#{category.posts.count}" + "件"
                .category__wrapper__main__block__righ__category.pb-3
                  = "ジャンル:#{@category.name}"

app/views/favorites/_favorite.html.haml
- if user_signed_in? && @post.user.id != current_user.id
  - if @post.favorited_by?(current_user) 
    = link_to(post_favorites_path(@post.id), method: :delete, remote: true)do 
      %span.iine__button__delete.px-1.py-1
        参考になった！
      %span.iine__count.ml-3.px-1.py-1
        = @post.favorites.count
  - else 
    = link_to(post_favorites_path(@post.id), method: :post, remote: true)do 
      %span.iine__button.px-1.py-1
        参考になった！
      %span.iine__count.ml-3.px-1.py-1
        = @post.favorites.count
-else 
  このレビューは#{@post.favorites.count}人の参考になっています！

app/views/posts/_header.html.haml
.wrapper
  .navbar.navbar-expand-lg.navbar-dark.bg-dark
    - @categories.each do |category|
      = link_to(categories_show_path(category))do
        %li.navbar__category
          = category.name

  .navbar__right.d-flex
    - if user_signed_in? 
      = link_to "感想を投稿する" , posts_new_anime_path, class:"nav-link__review"
      .navbar__right__menu#mypage  
        .navbar__right__menu__name
          = current_user.name 
          %span.navbar__right__menu__name__icon
            %i.fas.fa-sort-down
        %ul.navbar__right__menu__list#list
          %li= link_to "参考になった記事", user_reference_path(current_user), class: "nav-link__mypage__like" 
          %li= link_to "投稿した記事", user_path(current_user), class: "nav-link__mypage__post"
          %li= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-link__logout", data: { confirm: "ログアウトしますか？"}           
    - else
      = link_to "ログイン", new_user_session_path, method: :get,  class:"nav-link__login"
      = link_to "新規会員登録", new_user_registration_path, class:"nav-link__signup"      

  .header.d-flex.align-items-center.justify-content-around.shadow-sm
    .header__left.d-flex
      .header__left__title.d-flex.ml-3
        = link_to "アニレビュ", root_path
      .header__left__text.ml-5.mt-3
        理解が深まるレビューサイト！
        %br/
        自分に合ったアニメを探そう！
    .header__right.mr-5
      = form_with(url: anime_search_path, local: true, method: :get, class: "search__form") do |f|
        = f.text_field :search, placeholder:'タイトルを入力して下さい', class:"header__right__search" ,required: true
        = f.submit "検索", class: "header__right__btn"
        .header__right__text.mt-2
          ＃ワンピース   ＃NARUTO   ＃BLEACH  ＃とらドラ

app/views/posts/_index.html.haml
.main.py-3.px-3
  .main__left
    .main__left__text.py-2
      作品の感想
    -@posts.each do |post|
      .main__left__form
        = link_to(anime_path(post.anime), class: "image") do
          .main-review.mt-3
            = image_tag post.anime.image.url, class:"anime__image"
            .main-review__anime
              = post.anime.title.truncate(17)

        = link_to(anime_post_path(post.anime, post), class: "show") do
          .main__left__block
            .main-review__title
              = post.title
            .main-review__text
              = post.review.truncate(175)
            -if post.review.length >= 175
              = link_to '>>続きを読む', anime_post_path(post.anime, post), class:'main-review__text__link'
            .main__left__block__name
              = post.user.name
              %span.main__left__block__name__time
                = post.created_at.strftime("%Y年%m月%d日 %H時%M分")

              %span.main-review__rate
                評価:  
                %span{:id => "star-rate-#{post.id}"}
                :javascript
                  $('#star-rate-#{post.id}').raty({
                    size: 36,
                    starOff:  '#{asset_path('star-off.png')}',
                    starOn : '#{asset_path('star-on.png')}',
                    starHalf: '#{asset_path('star-half.png')}',
                    half: true,
                    readOnly: true,
                    score: #{post.rate}
                  });
              = post.rate
              %span.main__left__block__name__length
                = post.review.length.to_s + "文字"
    .pagenate              
      = paginate @posts  

app/views/posts/_right.html.haml
.main__right.mx-3
  .main__right__box
    レビュー数上位ランキング
    - @all_ranks.each.with_index(1) do |anime, i|
      %ul.main__right__box__list
        %li.main__right__box__list__rank
          =link_to(anime_path(anime), class: "rank") do
            .main__right__box__list__rank__best
              第#{i}位
            .main__right__box__list__rank__image.my-3
              = image_tag anime.image.url
            .main__right__box__list__rank__title
              = anime.title

            %span.right__review__rate
              評価:  
              %span{:id => "rate-#{anime.id}"}
              :javascript
                $('#rate-#{anime.id}').raty({
                  size: 36,
                  starOff:  '#{asset_path('star-off.png')}',
                  starOn : '#{asset_path('star-on.png')}',
                  starHalf: '#{asset_path('star-half.png')}',
                  half: true,
                  readOnly: true,
                  score: #{anime.posts.average(:rate).to_f.round(1)}  
                });
              = anime.posts.average(:rate).to_f.round(1)
              .right__review__rate__count
                口コミ
                = "#{anime.posts.count}" + "件"
              .right__review__rate__genre
                = "ジャンル:#{anime.category.name}"

  .main__right__genre
    .main__right__genre__text.mx-3.my-3
      作品を探す
    .main__right__genre__category
      - @categories.each do |category|
        = link_to(categories_show_path(category), class: "battle")do
          = category.name

app/views/posts/edit.html.haml
.user__edit.p-3.my-3 
  .user__edit__text.my-3
    感想を編集する
  .user__edit__block 
    %span.user__edit__block__left
      = image_tag @post.anime.image_url
    .user__edit__block__right
      .user__edit__block__right__title.mt-3      
        = @post.anime.title
      .user__edit__block__right__genre.mt-3
        = "ジャンル: #{@post.anime.category.name}"
  
  = form_for [@post], url: anime_post_path(@anime) do |f|
    .user__edit__form
      .user__edit__form__rate.mt-3.p-1#star
        = f.label :rate, '総合評価:', class: "user__edit__form__rate__label"
        = f.hidden_field :rate, id: :edit__star
      .user__edit__form__title
        = f.text_field :title, autofocus: true, class: "user__edit__form__title__field"
      .user__edit__form__review
        = f.text_area :review, autofocus: true, class: "user__edit__form__review__field", id: "edit__review", rows:"11", cols:"84"
      .user__edit__form__count#edit__count
        0文字
      .user__edit__form__submit
        = f.submit "投稿する", class: "user__edit__form__submit__btn"

:javascript
  $('#star').raty({
    size     : 36,
    starOff:  '#{asset_path('star-off.png')}',
    starOn : '#{asset_path('star-on.png')}',
    starHalf: '#{asset_path('star-half.png')}',
    scoreName: 'post[rate]',
    half: true,
    score: #{@post.rate}  
  });

app/views/posts/index.html.haml
.slick.border
  人気の作品
  -@anime.each do |anime|
    .slick__block
      = link_to(anime_path(anime), class: "slick__link") do
        .slick__image.my-4
          = image_tag asset_path(anime.image.url)
          .slick__image__tag
            = anime.category.name
          .slick__image__title.my-1
            = anime.title
= render partial: "index"
.main
  = render partial: "right"

app/views/posts/new.html.haml
.posts__new.p-3.my-3
  .posts__new__text
    感想を投稿する
  .posts__new__block
    %span.posts__new__block__left
      = image_tag @anime.image.url
    .posts__new__block__right
      .posts__new__block__right__title.mt-3
        = @anime.title
      .posts__new__block__right__genre.mt-3
        = "ジャンル: #{@anime.category.name}"
  = form_for [@post], url: anime_posts_path(@anime) do |f|
    .posts__new__block__form
      .posts__new__block__form__rate.mt-3.p-1#star
        = f.label :rate, '総合評価:', class: "posts__new__block__form__rate__label"
        = f.hidden_field :rate, id: :new__star
        = f.hidden_field :anime_id, value: @anime.id
      .posts__new__block__form__title
        = f.text_field :title, autofocus: true, class: "posts__new__block__form__title__field"
      .posts__new__block__form__review
        = f.text_area :review, autofocus: true, class: "posts__new__block__form__review__field",id: "new__anime__review",rows: "13", cols: "85"
      .posts__new__block__form__count#new__anime__count
        0文字
      .posts__new__block__form__submit
        = f.submit "投稿する", class: "posts__new__block__form__submit__btn"

= render partial: "rate"

app/views/posts/show.html.haml
.show__wrapper.pt-2
  .show__wrapper__main
    = link_to(anime_path(@anime), class: "show__wrapper__main__link")do
      .show__wrapper__main__anime.mb-3
        .show__wrapper__main__anime__image
          = image_tag @post.anime.image.url
        .show__wrapper__main__anime__item
          .show__wrapper__main__anime__item__title
            = @post.anime.title
          .show__wrapper__main__anime__item__count
            口コミ数
            = "#{@anime.posts.count}" + "件"
          .show__wrapper__main__anime__item__star
            %span.show__review__rate
              みんなの評価:  
              %span{:id => "show-rate-#{@post.id}"}
              :javascript
                $('#show-rate-#{@post.id}').raty({
                  size: 36,
                  starOff:  '#{asset_path('star-off.png')}',
                  starOn : '#{asset_path('star-on.png')}',
                  starHalf: '#{asset_path('star-half.png')}',
                  half: true,
                  readOnly: true,
                  score: #{@anime.posts.average(:rate).to_f.round(1)}  
                });
            = @anime.posts.average(:rate).to_f.round(1)
      
    .show__wrapper__main__review.mb-3
      .show__wrapper__main__review__header.px-3.py-3
        %ul.show__wrapper__main__review__header__left
          %li.show__wrapper__main__review__header__left__name
            = @post.user.name
          %li.show__wrapper__main__review__header__left__date
            = @post.created_at.strftime("%Y年%m月%d日 %H時%M分")
          %span.show__wrapper__main__review__header__left__count
            #{@post.favorites.count}
          %span.show__wrapper__main__review__header__left__right
            参考になった！
        .show__wrapper__main__review__header__title
          = @post.title
        %span.show__wrapper__main__review__header__rate
          評価：
          %span{:id => "personal-rate-#{@post.id}"}
          :javascript
            $('#personal-rate-#{@post.id}').raty({
              size: 36,
              starOff:  '#{asset_path('star-off.png')}',
              starOn : '#{asset_path('star-on.png')}',
              starHalf: '#{asset_path('star-half.png')}',
              half: true,
              readOnly: true,
              score: #{@post.rate}  
            });
          = @post.rate
        %span.show__wrapper__main__review__header__edit
          - if user_signed_in? && current_user.id == @post.user.id
            = link_to "[編集する]", edit_anime_post_path(@anime, @post), class: "show__wrapper__main__review__header__edit__post"
            = link_to "[削除する]", anime_post_path(@anime, @post), method: :delete, data: { confirm: '削除しますか？'}, class: "show__wrapper__main__review__header__destroy__post"
        .show__wrapper__main__review__header__text.mt-3
          = simple_format(@post.review)

        -# いいね機能
      .show__wrapper__main__review__good
        %div{:id => "favorites_buttons_#{@post.id}"}
          = render partial: 'favorites/favorite', locals: { post: @post}

      .show__wrapper__main__review__other
        .show__wrapper__main__review__other__text
          他のレビュアーの感想・評価     
          - @anime.posts.shuffle.first(3).each do |post|
            = link_to(anime_post_path(post.anime, post))do
              .show__wrapper__main__review__other__block.my-3
                .show__wrapper__main__review__other__block__title
                  = post.title
                .show__wrapper__main__review__other__block__text
                  = post.review.truncate(175)
                -if post.review.length >= 175
                  = link_to '>>続きを読む', anime_post_path(post.anime, post), class:'show__wrapper__main__review__other__block__text__link'
                .show__wrapper__main__review__other__block__name
                  = post.user.name
                  %span.show__wrapper__main__review__other__block__time.mx-3
                    = post.created_at.strftime("%Y年%m月%d日 %H時%M分")
                  %span.show__wrapper__main__review__other__block__rate.mx-1
                    評価:  
                    %span{:id => "other-rate-#{post.id}"}
                    :javascript
                      $('#other-rate-#{post.id}').raty({
                        size: 36,
                        starOff:  '#{asset_path('star-off.png')}',
                        starOn : '#{asset_path('star-on.png')}',
                        starHalf: '#{asset_path('star-half.png')}',
                        half: true,
                        readOnly: true,
                        score: #{post.rate}
                      });
                  = post.rate
                  %span.show__wrapper__main__review__other__block__length.mx-5
                    = post.review.length.to_s + "文字"


.main.flex 
  = render partial: 'right'
  

app/views/users/reference.html.haml
.user__reference.mb-3
  .user__reference__review.my-3
    参考になった感想
    %span.user__reference__review__count
      = "(#{@references.count}件)"
  .user__reference__main
    .user__reference__main__text.py-2
      作品の感想
    - @references.each do |reference|
      .user__reference__main__form
        = link_to(anime_path(reference.anime), class: "user__reference__main__form__link")do
          .user__reference__main__form__left
            = image_tag reference.anime.image.url, class: "user__reference__main__form__left__image"
            .user__reference__main__form__left__title
              = reference.anime.title.truncate(20)

          = link_to(anime_post_path(reference.anime, reference), class: "user__reference__main__form__post")do
            .user__reference__main__form__right
              .user__reference__main__form__right__title.mb-2
                = reference.title
              .user__reference__main__form__right__text
                = reference.review.truncate(175)
              -if reference.review.length >= 175
                = link_to '>>続きを読む', anime_post_path(reference.anime, reference), class: "user__reference__main__form__right__text__link"
              .user__reference__main__form__right__name
                = reference.user.name
                %span.user__reference__main__form__right__name__time
                  = reference.created_at.strftime("%Y年%m月%d日 %H時%M分")
                %span.user__reference__main__form__right__name__rate
                  評価:  
                  %span{:id => "user-reference-rate-#{reference.id}"}
                  :javascript
                    $('#user-reference-rate-#{reference.id}').raty({
                      size: 36,
                      starOff:  '#{asset_path('star-off.png')}',
                      starOn : '#{asset_path('star-on.png')}',
                      starHalf: '#{asset_path('star-half.png')}',
                      half: true,
                      readOnly: true,
                      score: #{reference.rate}
                    });
                = reference.rate
                %span.user__reference__main__form__right__name__length
                = reference.review.length.to_s + "文字" 